### ISSUE TITLE
Audio 100% again after SimpleAdjustableFairings staging

### ISSUE THREAD

**Issue by Gordon-Dry** [Tahvohck/KSP-Audio-Muffler-Redux#1]
I had just an occurance of a fairing (SimpleAdjustableFairings) being staged and from that moment on the muffling was disabled. Full volume sound. No exception written. 

This also happens when not staging but using the auto feature of SimpleAdjustableFairings.

**Comment by Tahvohck** [comment]
This is is a super old repo, I'm actually fairly certain that it was forked from a now non-public repo. The blowfishpro repo is probably the best place to follow through on this, so I'm going to close this issue.

**Comment by Gordon-Dry** [comment]
Oh, I see. I looked for forks and there were none so I assumed.
It's a confusing chaos.
Where did I get the latest working version from again? Hmm.
From here: https://github.com/Tahvohck/KSP-Audio-Muffler-Redux/releases

blowfishpro? I only see SerTheGreat. There is no repo of AudioMuffler from blowfishpro.
